.TH "DEF" 3 "2018年06月24日(日)" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEF
.SH SYNOPSIS
.br
.PP
.PP
\fBCHANNEL\fPを継承しています。
.SS "公開メンバ関数"

.in +1c
.ti -1c
.RI "\fBDEF\fP ()"
.br
.in -1c
.SH "詳解"
.PP 
 chanel\&.cpp の 26 行目に定義があります。
.SH "構築子と解体子"
.PP 
.SS "DEF::DEF ()\fC [inline]\fP"

.PP
 chanel\&.cpp の 28 行目に定義があります。
.PP
.nf
28 :CHANNEL("DEF局"){}
.fi


.SH "著者"
.PP 
 My Projectのソースコードから抽出しました。
