.TH "kadai.cpp" 3 "Sun Jun 24 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kadai.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdata\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFILEPATH\fP   '\&./input\&.txt'"
.br
.ti -1c
.RI "#define \fBLISTNUM\fP   100"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBdata\fP \fBlistdata\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FILEPATH   '\&./input\&.txt'"

.PP
Definition at line 8 of file kadai\&.cpp\&.
.SS "#define LISTNUM   100"

.PP
Definition at line 9 of file kadai\&.cpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBdata\fP  \fBlistdata\fP"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 24 of file kadai\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
